name: Build ByRKN Launcher EXE

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🧰 Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: 📦 Restore dependencies
        run: dotnet restore ./src/ByRKN_Launcher/ByRKN_Launcher.csproj

      - name: 🛠 Build project
        run: dotnet build ./src/ByRKN_Launcher/ByRKN_Launcher.csproj --configuration Release --no-restore

      - name: 🚀 Publish self-contained .exe
        run: dotnet publish ./src/ByRKN_Launcher/ByRKN_Launcher.csproj --configuration Release --output ./build --self-contained --runtime win-x64 /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true

      - name: 📤 Upload EXE Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ByRKN-Launcher
          path: ./build
