name: Build Windows EXE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # или замени на свою версию .NET

      - name: Restore dependencies
        run: dotnet restore ./src/ByRKNLauncher.csproj

      - name: Build
        run: dotnet build ./src/ByRKNLauncher.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./src/ByRKNLauncher.csproj --configuration Release --output ./output --self-contained --runtime win-x64 /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: ByRKN-Launcher
          path: ./output
