name: Build .NET WPF EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' # или 7.0.x если ты на .NET 7

    - name: Restore dependencies
      run: dotnet restore ./src/ByRKN_Launcher/ByRKN_Launcher.csproj

    - name: Build project
      run: dotnet build ./src/ByRKN_Launcher/ByRKN_Launcher.csproj -c Release --no-restore

    - name: Publish as EXE
      run: dotnet publish ./src/ByRKN_Launcher/ByRKN_Launcher.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -o ./output

    - name: Upload EXE Artifact
      uses: actions/upload-artifact@v3
      with:
        name: launcher-exe
        path: ./output
